name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Gradle Jar
        run: ./gradlew jar
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Plugin Jar
          path: ./build/libs/*.jar
